config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'materials/index'
    get 'materials/show'
  end
  devise_for :customer, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # ++++++++++++++++++++++++++++++++++++++++

  scope module: 'public' do
    # homes
    root to: 'homes#top'

    # customers
    resources :customers, only: [:edit, :destroy]
    get 'customers/my_chara' => 'customers#show'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'  => 'customers#withdraw'

    # characters
    resources :characters, only: [:new, :show, :create, :edit, :update, :destroy]
    get 'search' => 'characters#search'
    get 'tag_search' => 'characters#tag_search'
    get 'category_search' => 'characters#category_search'

    # categories
    resources :categories, only: [:index, :create, :update, :destroy]

    # tags
    resources :tags, only: [:index, :create, :update, :destroy]

    # inquiries
    resources :inquiries, only: [:new, :create, :update]

    # materials
    resources :materials, only: [:index, :create, :update, :destroy, :edit, :new, :show]
  end

  # ++++++++++++++++++++++++++++++++++++++++

  namespace :admin do
    # customers
    resources :customers, only: [:index, :update, :destroy]
    get 'customer_search' => 'customers#customer_search'

    # inquiries
    resources :inquiries, only: [:index, :show, :create]

    resources :answers, only: [:create]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]

  validates_uniqueness_of :name
  validates_presence_of :name

  has_many :categories, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_many :materials, dependent: :destroy

  def self.customer_name_search(customer_name)
    where(["name like?", "%#{customer_name}%"])
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value", { :value => name }]).first
    else
      where(conditions).first
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all

    if params[:is_active_true].present?
      @customers = Customer.where(is_active: 'true')
    end
    if params[:is_active_false].present?
      @customers = Customer.where(is_active: 'false')
    end
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to admin_customers_path
  end

  def customer_search
    @customers = Customer.customer_name_search(params[:customer_name])
    render "index"
  end

  private

  def customer_params
    params.require(:customer).permit(:is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div>

  <div>
    <%= form_with url: admin_customer_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :customer_name, value: @customer_name %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
  <div><%= link_to "すべて表示する", admin_customers_path %></div>
  <div>
    <span><%= link_to "有効の会員のみ表示する", admin_customers_path(is_active_true: 1) %></span>：
    <span><%= link_to "無効の会員のみ表示する", admin_customers_path(is_active_false: 1) %></span>
  </div>

  <div class="title">会員一覧</div>
  <div>
    <table>
      <thead>
        <tr>
          <th class="outline text-center">ID</th>
          <th class="outline text-center">ユーザ名</th>
          <th class="outline text-center">ステータス</th>
          <th class="outline text-center">変更</th>
          <th colspan="1" class="outline text-center"></th>
        </tr>
      </thead>

      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td class="outline text-center"><%= customer.id %></td>
          <td class="outline text-center"><%= customer.name %></td>
          <td class="outline text-center">
            <div>
            <% if customer.is_active %>
              <div>有効</div>
            <% else %>
              <div>退会</div>
            <% end %>
            </div>
          </td>
          <td class="outline text-center">
            <div>
            <% if customer.is_active %>
              <div><%= link_to "退会にする", admin_customer_path(customer.id, customer:{is_active: false}), method: :patch, "data-confirm" => "退会にしますか？", class: "btn btn-primary" %></div>
            <% else %>
              <div><%= link_to "有効にする", admin_customer_path(customer.id, customer:{is_active: true}), method: :patch, "data-confirm" => "有効にしますか？", class: "btn btn-primary" %></div>
            <% end %>
            </div>
          </td>
          <td class="outline text-center">
            <div><%= link_to "削除する", admin_customer_path(customer.id), method: :delete, "data-confirm" => "会員を完全に削除します。よろしいですか？", class: "btn btn-danger" %></div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>