config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'materials/index'
    get 'materials/show'
  end
  devise_for :customer, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # ++++++++++++++++++++++++++++++++++++++++

  scope module: 'public' do
    # homes
    root to: 'homes#top'

    # customers
    resources :customers, only: [:edit, :destroy]
    get 'customers/my_chara' => 'customers#show'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'  => 'customers#withdraw'

    # characters
    resources :characters, only: [:new, :show, :create, :edit, :update, :destroy]
    get 'search' => 'characters#search'
    get 'tag_search' => 'characters#tag_search'
    get 'category_search' => 'characters#category_search'

    # categories
    resources :categories, only: [:index, :create, :update, :destroy]

    # tags
    resources :tags, only: [:index, :create, :update, :destroy]

    # inquiries
    resources :inquiries, only: [:new, :create, :update]

    # materials
    resources :materials, only: [:index, :create, :update, :destroy, :edit, :new, :show]
  end

  # ++++++++++++++++++++++++++++++++++++++++

  namespace :admin do
    # customers
    resources :customers, only: [:index, :update, :destroy]
    get 'customer_search' => 'customers#customer_search'

    # inquiries
    resources :inquiries, only: [:index, :show, :create]

    resources :answers, only: [:create]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyChara</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/6691dd93a4.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <div class="width-100p">
        <!--ロゴ-->
        <h1><%= link_to "まいきゃら", root_path, class: 'logo' %></h1>

        <div class="width-100p">

          <ul>
            <!--管理者ログイン-->
            <% if admin_signed_in? %>
            <li><%= link_to "会員一覧", admin_customers_path, class: 'header-btn' %></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'header-btn' %></li>

            <!--会員ログイン-->
            <% elsif customer_signed_in? %>
            <div><%= current_customer.name %>　ログイン中</div>
            <li><%= link_to "まいきゃら一覧", customers_my_chara_path, class: 'header-btn' %></li>
            <li><%= link_to "タグ・カテゴリ", categories_path, class: 'header-btn' %></li>
            <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'header-btn' %></li>

            <!--共通ログアウト-->
            <% else %>
            <li><%= link_to "ログイン", new_customer_session_path, class: 'header-btn' %></li>

            <% end %>
          </ul>

        </div>

      </div>
    </header>

    <main>
      <div><%= yield %></div>
    </main>

    <footer class="width-100p overline">
      <div class="top-30"></div>
      <div class="text-center font-25 underline"><%= link_to "まいきゃら", root_path %></div>
    </footer>

  </body>
</html>